apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-sync-notification
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: sync-notification
          image: curlimages/curl
          command:
            - "curl"
            - "-X"
            - "POST"
            - "payload={\"channel\": \"#somechannel\", \"username\": \"hello\", \"text\": \"App Sync failed\", \"icon_emoji\": \":ghost:\"}"
            - "http://host.docker.internal:8080/api/argocdnotifications/"
      restartPolicy: Never
  backoffLimit: 2
