apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-sync-notification
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: sync-notification
          image: curlimages/curl
          command:
            - "curl"
            - "--location"
            - "http://host.docker.internal:8080/api/argocdnotifications"
            - "--data"
            - "{'App': '{{.app.metadata.name}}'}"
      restartPolicy: Never
  backoffLimit: 2
