apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-sync-notification
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: sync-notification
          image: curlimages/curl
          command:
            - "curl --location 'http://localhost:8080/api/argocdnotifications' --header 'Content-Type: application/json' --data '{ 'test': 'test'}'"

      restartPolicy: Never
  backoffLimit: 2
