apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-sync-notification
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: sync-notification
          image: curlimages/curl
          command:
            - "curl"
            - "-X"
            - "GET"
            - "http://localhost:8080/api/v1/healthcheck"
      restartPolicy: Never
  backoffLimit: 2
